export interface AgentDef {
  name: string
  role: string
  tools: string[]
  trigger: string
}

export interface AgentsMdData {
  systemName: string
  systemDescription: string
  globalRules: string[]
  agents: AgentDef[]
  handoffLogic: string
}

export function generateAgentsMd(data: AgentsMdData): string {
  const parts: string[] = []

  const title = data.systemName.trim() || "Multi-Agent System"
  parts.push(`# AGENTS.md — ${title}\n<!-- Generated by SuperMD · supermd.dev/agents-md -->`)

  if (data.systemDescription.trim()) {
    parts.push(`> ${data.systemDescription.trim()}`)
  }

  const rules = data.globalRules.map((r) => r.trim()).filter(Boolean)
  if (rules.length) {
    parts.push(`## Global Rules\n\n${rules.map((r) => `- ${r}`).join("\n")}`)
  }

  const agents = data.agents.filter((a) => a.name.trim() || a.role.trim())
  if (agents.length) {
    const agentBlocks = agents.map((agent) => {
      const lines: string[] = []
      lines.push(`### ${agent.name.trim() || "Unnamed Agent"}`)

      if (agent.role.trim()) {
        lines.push(agent.role.trim())
      }

      const tools = agent.tools.map((t) => t.trim()).filter(Boolean)
      if (tools.length) {
        lines.push(`**Tools:** ${tools.map((t) => `\`${t}\``).join(", ")}`)
      }

      if (agent.trigger.trim()) {
        lines.push(`**When to use:** ${agent.trigger.trim()}`)
      }

      return lines.join("\n\n")
    })

    parts.push(`## Agents\n\n${agentBlocks.join("\n\n---\n\n")}`)
  }

  if (data.handoffLogic.trim()) {
    parts.push(`## Handoff Logic\n\n${data.handoffLogic.trim()}`)
  }

  return parts.join("\n\n")
}
