export type RulesTarget = "cursor" | "copilot" | "windsurf"

export interface RulesFormData {
  language: string
  framework: string
  description: string
  conventions: string
  dos: string[]
  donts: string[]
  extra: string
}

export function getFilename(target: RulesTarget): string {
  switch (target) {
    case "cursor": return ".cursorrules"
    case "copilot": return "copilot-instructions.md"
    case "windsurf": return ".windsurfrules"
  }
}

export function generateRulesMd(data: RulesFormData, target: RulesTarget): string {
  const dos = data.dos.map((d) => d.trim()).filter(Boolean)
  const donts = data.donts.map((d) => d.trim()).filter(Boolean)
  const language = data.language.trim()
  const framework = data.framework.trim()
  const description = data.description.trim()
  const conventions = data.conventions.trim()
  const extra = data.extra.trim()

  const stackParts = [language, framework].filter(Boolean)

  if (target === "copilot") {
    return buildCopilot({ language, framework, description, conventions, dos, donts, extra, stackParts })
  }

  return buildCursorStyle({ language, framework, description, conventions, dos, donts, extra, stackParts }, target)
}

interface BuildArgs {
  language: string
  framework: string
  description: string
  conventions: string
  dos: string[]
  donts: string[]
  extra: string
  stackParts: string[]
}

function buildCursorStyle(d: BuildArgs, target: RulesTarget): string {
  const parts: string[] = []

  const label = target === "cursor" ? "Cursor" : "Windsurf"
  const expertLine = d.stackParts.length
    ? `You are an expert ${d.stackParts.join(" / ")} developer.`
    : "You are an expert software developer."

  parts.push(expertLine)

  if (d.description) {
    parts.push(d.description)
  }

  if (d.stackParts.length) {
    const stackLines = []
    if (d.language) stackLines.push(`- Language: ${d.language}`)
    if (d.framework) stackLines.push(`- Framework: ${d.framework}`)
    parts.push(`## Stack\n\n${stackLines.join("\n")}`)
  }

  if (d.conventions) {
    parts.push(`## Conventions\n\n${d.conventions}`)
  }

  if (d.dos.length) {
    parts.push(`## Always\n\n${d.dos.map((r) => `- ${r}`).join("\n")}`)
  }

  if (d.donts.length) {
    parts.push(`## Never\n\n${d.donts.map((r) => `- ${r}`).join("\n")}`)
  }

  if (d.extra) {
    parts.push(`## Extra\n\n${d.extra}`)
  }

  const header = target === "cursor"
    ? `# ${label} Rules\n# Generated by SuperMD · supermd.dev/rules-md\n`
    : `# ${label} Rules\n# Generated by SuperMD · supermd.dev/rules-md\n`

  return `${header}\n${parts.join("\n\n")}`
}

function buildCopilot(d: BuildArgs): string {
  const parts: string[] = []

  parts.push("# GitHub Copilot Instructions\n<!-- Generated by SuperMD · supermd.dev/rules-md -->")

  if (d.description) {
    parts.push(d.description)
  }

  if (d.stackParts.length) {
    const stackLines = []
    if (d.language) stackLines.push(`- **Language:** ${d.language}`)
    if (d.framework) stackLines.push(`- **Framework:** ${d.framework}`)
    parts.push(`## Tech Stack\n\n${stackLines.join("\n")}`)
  }

  if (d.conventions) {
    parts.push(`## Coding Standards\n\n${d.conventions}`)
  }

  if (d.dos.length) {
    parts.push(`## Always\n\n${d.dos.map((r) => `- ${r}`).join("\n")}`)
  }

  if (d.donts.length) {
    parts.push(`## Avoid\n\n${d.donts.map((r) => `- ${r}`).join("\n")}`)
  }

  if (d.extra) {
    parts.push(`## Additional Instructions\n\n${d.extra}`)
  }

  return parts.join("\n\n")
}
